Document: vibe2modules
Title: Debian vibe2modules Manual
Author: <insert document author here>
Abstract: This manual describes what vibe2modules is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/vibe2modules/vibe2modules.sgml.gz

Format: postscript
Files: /usr/share/doc/vibe2modules/vibe2modules.ps.gz

Format: text
Files: /usr/share/doc/vibe2modules/vibe2modules.text.gz

Format: HTML
Index: /usr/share/doc/vibe2modules/html/index.html
Files: /usr/share/doc/vibe2modules/html/*.html
